/**
 * Generate Supabase seed SQL from mockData.ts
 * Run: node --experimental-vm-modules scripts/generate-seed.mjs
 *
 * This reads the mockData module and outputs INSERT statements.
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, '..');

// Read mockData as text and eval the exports we need
const mockDataPath = join(projectRoot, 'src/services/mockData.ts');
const mockDataSrc = readFileSync(mockDataPath, 'utf-8');

// We'll use a simple approach: extract the data via regex/string parsing
// since the file uses TS syntax that Node can't import directly.

// Instead, let's use a transpile approach with esbuild or similar
// Actually, the simplest approach is to parse the file structure directly

// Let's read the conversationEngine to get the scene->script mapping
const enginePath = join(projectRoot, 'src/services/conversationEngine.ts');
const engineSrc = readFileSync(enginePath, 'utf-8');

console.log('Reading mockData and generating seed SQL...');

// We need to use a different approach - use tsx or ts-node to actually load the module
// Check if tsx is available
import { execSync } from 'child_process';

// Use a temp JS file that requires the transpiled mockData
const tempScript = `
const { WORDS, SCENES, CAFE_CONVERSATION, PROFESSIONAL_CONVERSATION, SOCIAL_CONVERSATION,
  IELTS_CONVERSATION, TOEIC_CONVERSATION, EMAIL_FOLLOWUP_CONVERSATION,
  PERFORMANCE_REVIEW_CONVERSATION, NETWORKING_CONFERENCE_CONVERSATION,
  GAMING_CONVERSATION, MOVIE_NIGHT_CONVERSATION, SOCIAL_MEDIA_CONVERSATION } = require('./src/services/mockData');

const sceneScriptMap = {
  'scene-cafe-survival': CAFE_CONVERSATION,
  'scene-cafe-professional': PROFESSIONAL_CONVERSATION,
  'scene-cafe-social': SOCIAL_CONVERSATION,
  'scene-doctor-survival': CAFE_CONVERSATION,
  'scene-meeting-professional': PROFESSIONAL_CONVERSATION,
  'scene-hanging-out-social': SOCIAL_CONVERSATION,
  'scene-ielts-practice': IELTS_CONVERSATION,
  'scene-toeic-practice': TOEIC_CONVERSATION,
  'scene-email-followup-professional': EMAIL_FOLLOWUP_CONVERSATION,
  'scene-performance-review-professional': PERFORMANCE_REVIEW_CONVERSATION,
  'scene-networking-conference-professional': NETWORKING_CONFERENCE_CONVERSATION,
  'scene-gaming-social': GAMING_CONVERSATION,
  'scene-movie-night-social': MOVIE_NIGHT_CONVERSATION,
  'scene-social-media-social': SOCIAL_MEDIA_CONVERSATION,
};

function escapeSql(str) {
  return str.replace(/'/g, "''");
}

function escapeJson(str) {
  return str.replace(/\\\\/g, '\\\\\\\\').replace(/'/g, "''");
}

const lines = [];

// Header
lines.push('-- Daily English: Seed Data from mockData.ts');
lines.push('-- Generated by scripts/generate-seed.mjs');
lines.push('-- All inserts are idempotent (ON CONFLICT DO NOTHING)');
lines.push('');
lines.push('-- Set default difficulty for words');
lines.push('');

// WORDS
lines.push('-- ============================================');
lines.push('-- WORDS');
lines.push('-- ============================================');
const wordEntries = Object.entries(WORDS);
for (const [key, word] of wordEntries) {
  const isNew = word.isNew ? 'TRUE' : 'FALSE';
  lines.push(\`INSERT INTO words (id, lemma, pos, frequency_rank, difficulty_level, is_new, created_at) VALUES ('\${escapeSql(key)}', '\${escapeSql(word.lemma)}', '\${escapeSql(word.pos)}', NULL, 'beginner', \${isNew}, now()) ON CONFLICT (id) DO NOTHING;\`);
}
lines.push('');

// WORD MODE ENTRIES
lines.push('-- ============================================');
lines.push('-- WORD MODE ENTRIES');
lines.push('-- ============================================');
for (const [key, word] of wordEntries) {
  for (const [modeCode, entry] of Object.entries(word.modeEntries)) {
    lines.push(\`INSERT INTO word_mode_entries (id, word_id, mode_code, meaning_context, register, example_sentence, example_context, audio_id) VALUES ('\${escapeSql(entry.id)}', '\${escapeSql(key)}', '\${escapeSql(modeCode)}', '\${escapeSql(entry.meaning_context)}', '\${escapeSql(entry.register)}', '\${escapeSql(entry.example_sentence)}', '\${escapeSql(entry.example_context)}', NULL) ON CONFLICT (id) DO NOTHING;\`);
  }
}
lines.push('');

// SCENES
lines.push('-- ============================================');
lines.push('-- SCENES');
lines.push('-- ============================================');
const sceneEntries = Object.entries(SCENES);
for (const [key, scene] of sceneEntries) {
  const targetIds = scene.newWords.map(w => w.id);
  const reviewIds = scene.reviewWords.map(w => w.id);
  const targetArray = "ARRAY['" + targetIds.join("','") + "']";
  const reviewArray = "ARRAY['" + reviewIds.join("','") + "']";
  lines.push(\`INSERT INTO scenes (id, track_code, mode_code, title, description, target_word_ids, review_word_ids, dialogue_text, audio_url, created_at) VALUES ('\${escapeSql(key)}', '\${escapeSql(scene.modeCode)}', '\${escapeSql(scene.modeCode)}', '\${escapeSql(scene.title)}', '\${escapeSql(scene.description)}', \${targetArray}, \${reviewArray}, '\${escapeSql(scene.dialogueText)}', NULL, now()) ON CONFLICT (id) DO NOTHING;\`);
}
lines.push('');

// CONVERSATION SCRIPTS
lines.push('-- ============================================');
lines.push('-- CONVERSATION SCRIPTS (stored as JSONB)');
lines.push('-- ============================================');
for (const [sceneId, script] of Object.entries(sceneScriptMap)) {
  const jsonStr = escapeJson(JSON.stringify(script));
  lines.push(\`INSERT INTO conversation_scripts (scene_id, script_data) VALUES ('\${escapeSql(sceneId)}', '\${jsonStr}'::jsonb) ON CONFLICT (scene_id) DO NOTHING;\`);
}
lines.push('');

console.log(\`Generated: \${wordEntries.length} words, \${sceneEntries.length} scenes, \${Object.keys(sceneScriptMap).length} conversation scripts\`);

process.stdout.write(lines.join('\\n'));
`;

// Write temp script and run it
const tempFile = join(projectRoot, '_temp_seed_gen.cjs');
writeFileSync(tempFile, tempScript);

try {
  // Run with the babel config that handles TS
  const result = execSync(
    `npx ts-node --compiler-options '{"module":"commonjs","esModuleInterop":true}' -e "require('./_temp_seed_gen.cjs')" 2>/dev/null || node _temp_seed_gen.cjs`,
    { cwd: projectRoot, encoding: 'utf-8', maxBuffer: 10 * 1024 * 1024 }
  );

  const seedPath = join(projectRoot, 'supabase/seed.sql');
  writeFileSync(seedPath, result);
  console.log(`Seed SQL written to ${seedPath}`);
  console.log(`Lines: ${result.split('\n').length}`);
} catch (err) {
  console.error('Error generating seed:', err.message);
  // Try alternative approach - just run node directly
  try {
    const result = execSync(`node _temp_seed_gen.cjs`, {
      cwd: projectRoot,
      encoding: 'utf-8',
      maxBuffer: 10 * 1024 * 1024
    });
    const seedPath = join(projectRoot, 'supabase/seed.sql');
    writeFileSync(seedPath, result);
    console.log(`Seed SQL written to ${seedPath}`);
  } catch (err2) {
    console.error('Alternative also failed:', err2.message);
  }
}

// Clean up temp file
import { unlinkSync } from 'fs';
try { unlinkSync(tempFile); } catch {}